<a href="https://colab.research.google.com/github/JakeOh/202007_itw_bd18/blob/master/lab_ml/ml04_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
iris['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [5]:
iris['feature_names']  # DataFrame의 컬럼 이름으로 사용할 수 있는 배열.

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris['target_names']  # DataFrame의 카테고리형 변수의 클래스.

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
X, y = iris['data'], iris['target']
X.shape, y.shape

((150, 4), (150,))

In [10]:
type(X)

numpy.ndarray

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

* 선형 대수(Linear Algebra): 벡터 스페이스(Vector Space)를 다루는 수학의 한 분야.

In [13]:
X[0]  # sl=5.1, sw=3.5, pl=1.4, pw=0.2인 붓꽃 샘플 -> (수학) 4차원 벡터 -> (Python) 1d-array

array([5.1, 3.5, 1.4, 0.2])

In [12]:
X[:5]  # 여러개의 붓꽃 샘플(데이터 프레임) -> (수학) 행렬(Matrix) -> (Python) 2d-array

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

* 벡터의 크기(norm): 원점에서 벡터까지 거리

In [21]:
def vector_norm(v):
    """v = [v_1, v_2, ..., v_n] 일 때, 
    norm = sqrt(sum_i[v_i ** 2])를 계산해서 리턴."""
    squares = [x ** 2 for x in v]
    sum_of_squares = np.sum(squares)
    norm = np.sqrt(sum_of_squares)
    # norm = np.sqrt(np.sum(x**2 for x in v))
    return norm

In [22]:
vector_norm([-1])  # 1차원 벡터: 원소가 1개인 1d-array

1.0

In [23]:
vector_norm([1, 1])  # 2차원 벡터: 원소가 2개인 1d-array

1.4142135623730951

In [24]:
vector_norm(X[0])

6.345076831686122

In [25]:
np.linalg.norm(X[0])

6.345076831686122

* 단위 벡터(unit vector): 크기(norm)가 1인 벡터. v / ||v||

In [29]:
v = np.array([1, 1])
v

array([1, 1])

In [30]:
v_unit = v / np.linalg.norm(v)  # v * (1 / norm)
v_unit

array([0.70710678, 0.70710678])

In [31]:
np.linalg.norm(v_unit)

0.9999999999999999

* 벡터들의 덧셈: 벡터들의 원소별로(element-wise) 각각 덧셈을 수행.
* 벡터들의 덧셈이 가능하려면 벡터의 차원이 같아야 함(벡터의 원소의 개수가 같아야 함).
* numpy arrary + 연산

In [32]:
u = np.array([1, 5])
v = np.array([2, 3])
u + v

array([3, 8])

* 스칼라 곱(Scalar Multiplication): 벡터의 각 원소에(element-wise) 스칼라(scalar)를 곱해 주는 것.
* numpy array의 * 연산

In [33]:
1.5 * u

array([1.5, 7.5])

In [34]:
u * 1.5

array([1.5, 7.5])

* 벡터의 점곱, 내적(Dot Product, Inner Product)
* numpy.dot() 함수, numpy.ndarray.dot() 메서드, numpy의 @ 연산자

In [35]:
def vector_dot_product(u, v):
    """u = [u_1, u_2, ..., u_n], v = [v_1, v_2, ..., v_n] 일 때,
    u dot v = u_1 * v_1 + u_2 * v_2 + ... + u_n * v_n = sum_i[u_i * v_i]
    """
    return np.sum([ui * vi for ui, vi in zip(u, v)])

In [36]:
u, v

(array([1, 5]), array([2, 3]))

In [37]:
vector_dot_product(u, v)  # 1*2 + 5*3

17

In [38]:
# numpy.dot() 함수
np.dot(u, v)

17

In [39]:
# numpy.ndarray.dot() 메서드
u.dot(v)

17

In [40]:
u @ v

17

* 행렬(Matrix) -> numpy 2d-array

In [41]:
M = np.array([
              [1, 2, 3],
              [4, 5, 6]
])
M  # 2x3 Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
M.shape  # (row 개수, column 개수)

(2, 3)

* 행렬의 인덱스: M[i, j]
* (n, m) 모양(shape)의 2d-array에서 인덱스: 0 <= i < n, 0 <= j < m

In [43]:
# 행렬에서 원소 1개 선택
M[1, 2]  #> 6

6

In [44]:
# 행렬에서 row (vector) 선택
M[1]

array([4, 5, 6])

In [45]:
M[1, :]

array([4, 5, 6])

In [46]:
# 행렬에서 column (vector) 선택
M[:, 1]

array([2, 5])

* numpy ndarray 객체는 행벡터(row vector), 열벡터(column vector)를 구분하지 않고, 1d-array로만 표시.
* scikit-learn 패키지를 사용할 때, 행벡터를 행의 개수가 1개인 2d-array로 만들고, 열벡터는 열의 개수가 1개인 2d-array로 만들어야 되는 경우가 있음.

In [47]:
M[1:2, :]  # 1 <= i < 2, 0 <= j < end
#> row vector 2d-array

array([[4, 5, 6]])

In [48]:
M[:, 1:2]  # 0 <= i < end, 1 <= j < 2
# column vector 2d-array

array([[2],
       [5]])

* 정사각행렬(square matrix): 행(row)과 열(column)의 개수가 같은 행렬
* 대각행렬(diagonal matrix): 대각선 성분(원소)이 아닌 원소들은 모두 0인 정사각 행렬.

In [50]:
np.diag([1, 2, 3])  # np.diag(1d-array/1d-list): 대각행렬 만듦.

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [51]:
np.diag([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])
# np.diag(2d-array/2d-list): 대각선 성분들로 이루어진 1d-array 반환.

array([1, 5, 9])

* 항등 행렬(identity matrix): 대각선 성분이 모두 1인 정사각 행렬.

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* 행렬의 덧셈: 같은 인덱스의 원소들끼리(element-wise) 덧셈.
* S[i, j] = A[i, j] + B[i, j]
* numpy + 연산

In [54]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
B = np.arange(10, 70, 10).reshape(2, 3)
B

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
A + B

array([[11, 22, 33],
       [44, 55, 66]])

* 행렬의 스칼라 곱(scalar multiplication): 스칼라(scalar)를 행렬의 각 원소에 곱하는 것.
* numpy * 연산자

In [57]:
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
A * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

* 행렬의 곱셈(Matrix Multiplication) - Dot Product(점곱), Inner Product(내적)
* 두 행렬 A와 B의 곱 AB: 행렬 A의 row vector와 행렬 B의 column vector의 내적들로 이루어짐.
* AB: 행렬 A의 열(column)의 개수와 행렬 B의 행(row)의 개수가 같아야 함.
* 일반적으로, AB != BA
* numpy.dot() 함수, numpy.ndarray.dot() 메서드, numpy @ 연산자

In [59]:
A = np.arange(1, 7).reshape(2, 3)
A  # (2, 3) 행렬

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
B = np.array([1, 2] * 3).reshape(3, 2)
B  # (3, 2) 행렬

array([[1, 2],
       [1, 2],
       [1, 2]])

In [61]:
np.dot(A, B)  # numpy.dot() 함수

array([[ 6, 12],
       [15, 30]])

In [62]:
A.dot(B)  # numpy.ndarray.dot() 메서드

array([[ 6, 12],
       [15, 30]])

In [63]:
A @ B  # (2, 3) @ (3, 2) = (2, 2)

array([[ 6, 12],
       [15, 30]])

In [64]:
B @ A  # (3, 2) @ (2, 3) = (3, 3)

array([[ 9, 12, 15],
       [ 9, 12, 15],
       [ 9, 12, 15]])

* 항등 행렬: `A @ I = A`, `I @ A = A`

In [65]:
A  # (2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# A @ I
A @ np.eye(3, dtype=np.int)  # (3, 3) 항등 행렬

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# I @ A
np.eye(2, dtype=np.int) @ A  # (2, 2) 항등 행렬

array([[1, 2, 3],
       [4, 5, 6]])

* 전치 행렬(Transpose): 행과 열을 바꾼 행렬.
* numpy.ndarry.T 속성(attribute)

In [73]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

* numpy 1d-array와 수학의 row vector는 미묘한 차이가 있다!

In [75]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [76]:
a.T  #> 1-d array
# 1d-array의 Transpose는 컬럼이 1개인 2d-array가 되지 않는다!

array([1, 2, 3])

* numpy 1d-array를 2d-array로 변환 => row vector <--(transpose)--> column vector

In [79]:
A = np.array([a])
A  #> 행(row)이 1개인 2d-array

array([[1, 2, 3]])

In [80]:
A.T

array([[1],
       [2],
       [3]])

In [82]:
a[np.newaxis, :]  # 1d-array -> row vector

array([[1, 2, 3]])

In [84]:
a[:, np.newaxis]  # 1d-array -> column vector

array([[1],
       [2],
       [3]])

* 역행렬(Inverse Matrix): 행렬 A가 정사각행렬일 때, `A @ X = X @ A = I`을 만족하는 정사각행렬 X를 행렬 A의 역행렬이라고 함.
* 모든 정사각행렬이 역행렬을 갖지는 않음.
* 특이행렬(Singular Matrix): 역행렬을 갖지 않는 정사각행렬.
* numpy.linalg.inv() 함수

In [85]:
A = np.arange(1, 5).reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [86]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [87]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [88]:
A_inv @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [91]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 0]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [92]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.77777778,  0.88888889, -0.11111111],
       [ 1.55555556, -0.77777778,  0.22222222],
       [-0.11111111,  0.22222222, -0.11111111]])

In [93]:
A @ A_inv

array([[ 1.00000000e+00,  5.55111512e-17,  1.38777878e-17],
       [ 5.55111512e-17,  1.00000000e+00,  2.77555756e-17],
       [ 1.77635684e-15, -8.88178420e-16,  1.00000000e+00]])

In [94]:
A_inv @ A

array([[ 1.00000000e+00, -1.11022302e-16,  0.00000000e+00],
       [ 8.32667268e-17,  1.00000000e+00,  2.22044605e-16],
       [ 6.93889390e-17,  0.00000000e+00,  1.00000000e+00]])

* 행렬의 Determinant: det(A), |A|
* numpy.linalg.det() 함수
* det 값이 0이면 역행렬이 존재하지 않음!

In [95]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [96]:
np.linalg.det(A)  # det(A) = 1 * 4 - 2 * 3 = -2

-2.0000000000000004

In [97]:
A = np.array([[1, 2],
              [2, 4]])
A

array([[1, 2],
       [2, 4]])

In [98]:
np.linalg.det(A)  # det(A) = 1 * 4 - 2 * 2 = 0

0.0

In [ ]:
# np.linalg.inv(A)  # det=0 이면, 역행렬이 존재하지 않음 -> singular matrix

In [100]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.det(A)

0.0

* 선형 회귀(Linear Regression)에서 선형 대수 응용.

In [101]:
x = np.array([1, 2, 3]).reshape((3, 1))
x

array([[1],
       [2],
       [3]])

In [102]:
y = np.array([3, 5, 7]).reshape((3, 1))
y

array([[3],
       [5],
       [7]])

```
3 = a * 1 + b
5 = a * 2 + b
7 = a * 3 + b
```
목적: a와 b를 찾는다.

In [103]:
w = np.array([2, 1]).reshape(2, 1)
w

array([[2],
       [1]])

In [104]:
X = np.c_[x, np.ones(shape=(3, 1))]
X

array([[1., 1.],
       [2., 1.],
       [3., 1.]])

In [105]:
X @ w  # y = X @ w

array([[3.],
       [5.],
       [7.]])

In [106]:
w2 = np.linalg.inv(X.T @ X) @ X.T @ y  # 정규 방정식(normal equation)
w2

array([[2.],
       [1.]])

In [ ]:
x = 3 * np.random.rand(100, 1)  # (100, 1) column vector
y = 4 + 3 * x + np.random.randn(100, 1)  # (100, 1) column vector

1. y ~ x scatter plot을 그리세요.
2. 데이터 x, y를 y = theta0 + theta1 * x 선형 회귀 방정식으로 설명하려고 할 때, theta0와 theta1을 정규 방정식으로 찾으세요.
3. 1번의 scatter plot에 선형 회귀 방정식 직선을 추가해서 그리세요.